# https://github.com/docker/build-push-action
name: data.table

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'data.table Version'
        required: true
        default: '1.14.2'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./data.table/Dockerfile
          push: true
          build-args: |
            version=${{ github.event.inputs.version }}
          tags: ghcr.io/juyeongkim/data.table:${{ github.event.inputs.version }}
